FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN RUN pip install --no-cache-dir --timeout 100 \
    -i https://mirror.yandex.ru/pypi/simple/ \
    -r requirements.txt

COPY . .

# Copy services directory for embedder and search
#COPY ../../services /opt/researchai/services

EXPOSE 8000

# Run the application
CMD ["uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8000"]